"use client";

import { useConsent } from "@/lib/consent";
import Icon from "@/components/Icon";

export default function ConsentPage() {
  const { giveConsent } = useConsent();

  return (
    <div className="min-h-screen bg-slate-50 flex items-center justify-center p-6">
      <div className="max-w-2xl w-full bg-white rounded-2xl shadow-sm border border-slate-200 p-8">
        <div className="text-center mb-8">
          <span className="inline-grid place-items-center w-11 h-11 rounded-xl bg-teal-600 text-white mb-3">
            <Icon name="activity" size={24} />
          </span>
          <h1 className="text-2xl font-semibold tracking-tight text-slate-800">
            MatchMyCancer<span className="text-teal-600">.ai</span>
          </h1>
          <p className="text-slate-500 mt-2">Please read before continuing</p>
        </div>

        <div className="bg-amber-50 border border-amber-200 rounded-xl p-6 mb-4">
          <h2 className="flex items-center gap-2 font-semibold text-amber-800 mb-3">
            <Icon name="alert" size={20} /> This is not medical advice
          </h2>
          <ul className="text-sm text-amber-700 space-y-2 list-disc list-inside">
            <li>This tool provides <strong>educational information only</strong> — it does not diagnose, prescribe, or recommend treatment.</li>
            <li>Results are generated by AI from your uploaded report and public databases (FDA labels, ClinicalTrials.gov, OncoKB).</li>
            <li>AI can miss, misinterpret, or hallucinate findings. Every claim links to the source text in your report — verify it yourself.</li>
            <li><strong>Always discuss any findings with your oncologist before acting on them.</strong></li>
          </ul>
        </div>

        <div className="bg-teal-50 border border-teal-200 rounded-xl p-6 mb-6">
          <h2 className="flex items-center gap-2 font-semibold text-teal-800 mb-3">
            <Icon name="lock" size={20} /> Your data
          </h2>
          <ul className="text-sm text-teal-800/90 space-y-2 list-disc list-inside">
            <li>Your uploaded document is processed <strong>in memory only</strong> — never written to disk.</li>
            <li>No account, no tracking, no persistent storage of your report.</li>
            <li>Results live only in your browser session and clear when you close the tab.</li>
          </ul>
        </div>

        <button
          onClick={giveConsent}
          className="w-full inline-flex items-center justify-center gap-2 bg-teal-600 text-white font-medium py-3 rounded-xl hover:bg-teal-700 transition-colors text-lg"
        >
          I understand — continue to upload
          <Icon name="arrowRight" size={20} />
        </button>

        <p className="text-center text-xs text-slate-400 mt-4">
          By continuing, you acknowledge the above and consent to AI processing of your uploaded document.
        </p>
      </div>
    </div>
  );
}
